10.md
README.md

optional is probably better than ~mandatory~  <grin>

Add NIP-10 to README

---

13.md
README.md

Proof of work for nostr events! I also fixed some other minor readme stuff.

NIP-13: Proof of Work

---

05.md

JS Nostr apps such as Branle may not be able to load `nostr.json` files due to CORS policies.  Update NIP05 to warn about this and provide hints for troubleshooting and fixing the issue.
I think this is the best way to address a [confusion](https://branle.netlify.app/event/f0d79c9bd1795b9c2a7511313bd7ad6f96350aa3f4045a8a69829cc0ff042fd4) I had trying to add my NIP05 identifier to a Branle instance where I kept receiving an error.  It also implies that other Nostr apps may be able to load `nostr.json` files that Branle and other pure-JS apps won't be able to load, which may produce some user confusion.
Note: I'm not a webdev, I might not be describing CORS stuff accurately.

NIP05: warn about CORS policies that may inhibit JS apps

---

15.md

This NIP specifies how relays may communicate to clients when all stored events have been sent. The motivation for this NIP is to reduce complexity (timeouts to make sure "we got all events").
This document was modified from NIP-12 heavily.

NIP15: End of Stored Events Notice

---

16.md

This NIP allows events to be marked replaceable/ephemeral which allows building applications that may rely on a single latest state or that may want to only send events to currently subscribed clients without them being persisted, both which reduce load on relay storage.

NIP16: Event Treatment

---

01.md

###Justification:  
In order for clients to make use of the `@username` syntax implied by NIP-08 we need some way to be able to reasonably parse those names.  This mechanisms is so standard that I don't think anyone will be surprised.  If we decide we need a better name field, we could add `formal_name` to the metadata.  
This is the pattern i've used in `more-speech`
Thoughts?

update to nip01 to specify syntax for usernames.

---

22.md
README.md

For relays to set limits on acceptable created_at times for events
Formatted: https://github.com/jeffthibault/nips/blob/nip22-unacceptable-event-time/22.md
Previous: #21

NIP-22: event created_at limits

---

28.md

Let's also disrupt Telegram, FB Messenger, WhatsApp, WeChat, et al.
[Link to NIP-28](https://github.com/nostr-protocol/nips/blob/af6893145f9a4a63be3d90beffbcfd4d90e872ae/28.md)

NIP-28: Public Chat

---

README.md

Simply links to the now-merged NIP-28 (Public Chat) in the main README.

add NIP-28 link and kinds in README

---

26.md

This NIP defines how events should be verified and signed to support generating events on behalf of someone else. It should be possible to sign Nostr events from other keypairs.
Another application of this proposal is to abstract away the use of the 'root' keypairs when interacting with clients. For example, a user could generate new keypairs for each client they wish to use and authorize those keypairs to generate events on behalf of their root pubkey, where the root keypair is stored in cold storage. 
I understand that this is a significant change to the protocol, so any feedback here is welcome.

NIP-26: Delegated Event Signing

---

01.md

Fix typo on NIP 01

---

10.md

Fixed typo referencing 'relay-id' instead of 'reply-id'.

Fixed typo referencing 'relay-id' instead of 'reply-id'.

---

16.md

A newer replaceable event must be signed by the same key.

nip16: clarify about the signers of replaceable events

---

20.md
README.md

When submitting events to relays, clients currently have no way to know if an event was successfully committed to the database. This NIP introduces the concept of command results which are like NOTICE's except provide more information about if an event was accepted or rejected.
[Doc](https://github.com/nostr-protocol/nips/blob/c510e646d0fd5bfa56a044756182cc10ad7e494d/20.md)
An earlier draft of this proposal is implemented on `nostr-rs-relay` on this branch:
https://git.sr.ht/~gheartsfield/nostr-rs-relay/log/feat-notice-like-responses
Will update it soon to match the NIP once this is reviewed.

NIP-20: Command Results

---

09.md

- change "MAY" to "SHOULD" for removing referenced events
- suggest indefinite retention for deletion events on relays
- include recommendation for clients to rebroadcast deletion events to relays
fixes #61

stronger wording for relay deletion behavior

---

01.md

Existing language of "indentation" implies line breaks.
After looking at other people's code and interacting with relays it became clear people were not putting in line breaks when taking the signature.  So either the NIP should be reworded, or everybody is doing it wrong.

Reword NIP-01 to clarify no line breaks.

---

01.md
16.md

So that people aren't trying to put json or any other nonsense in kind 1 events.

Clarify use of kind 1 and kind 1000-10000

---

22.md

When I first read NIP-22 I was concerned that many relays would reject events that were not created recently. I propose adding this small note so that relay developers/operators can more easily be aware of what use cases they are (or are not) catering to.

Note on nip-22 about moving old posts to a new relay

---

01.md

Most implementation ignore this line. Enforcing that usernames not include spaces, special chracters, unicode, emojis, etc has no benefit and is unnecessarily user hostile.

Remove username pattern requirements

---

19.md

With an extra section for TLV-encoded arbitrary metadata. Let me know what you think.
I think this will be very much necessary, for example, for Minds-like integrations through which some profiles and events will generally be only accessible from one master relay from each platform (e.g. the Minds relay). @ottman @harding what do you think?
And also when the network grows and we start to see more segregation of contents between relays, this makes it easier for people to share their profiles, without having to say: "my pubkey is X, and please make sure to add relay Z to your client".
https://github.com/nostr-protocol/nips/blob/ce4869b9404b9c588ef92353999cbe787cb679c3/19.md
Is this correct @jb55? What else are you bech32-encoding? Event ids?

add NIP-19: bech32-encoding of stuff.

---

01.md

Surely must be a typo? Event 2 kind should recommend a websocket URI/URL for a relay.

LUD-01: fix typo for the desc of event kind 2

---

35.md

Fixing a JSON comma
Also thought it was worthwhile to mention that if a webserver dynamically serves a public key based on the query string, it should also include the relays in the response.

NIP-35 fixes

---

10.md

AFAIK different clients implement this differently. Some add both marker tags (`root` and `reply`) for direct replies, some add one, some add the other.
This PR suggests a way to clarify that confusion.

NIP-10: Clarify marked e-tags for direct replies

---

05.md

There has been some confusion about whether npub keys are supported by this spec. According to @fiatjaf only Hex keys are supported. https://twitter.com/fiatjaf/status/1608606752987316224?s=20&t=6fJLD3077byuoTm96kva1g

Make it clear that NIP-05 Keys should be in Hex

---

16.md
33.md

NIP-33 allows for parameterized replaceable events which allow replacement by the `d` tag and the kind instead of just the kind.

Add NIP-33 Parameterized replaceable events

---

05.md

Currently the header check is case sensitive so will fail for servers which are configured correctly but with lowercase headers.
Before:
```
$ curl -sI https://static.lu.ke/.well-known/nostr.json | grep ^Access-Control
```
After:
```
$ curl -sI https://static.lu.ke/.well-known/nostr.json | grep -i ^Access-Control
access-control-allow-origin: *
```

NIP05 Improve CORS header check command

---

26.md

I'm not sure what the current `created_at>1640995200` condition is accomplishing (unless there's some worry that relays might accept back-dated events?).
It seems more useful to demonstrate that the delegation token can expire after X time (e.g. a 30-day authorization).

NIP-26: Change example condition to expire at a future date

---

10.md

I think that adding a mention marker would eliminate ambiguity for clients supporting both the deprecated and preferred conventions. I also think that this would allow for extensibility in adding new types of event mentions (for example if we want to add context for a note).
just thought I would throw this out there, let me know what you think.

Update NIP-10: add 'mention' marker

---

02.md
09.md

In NIP-09, my reading of the spec leads me to believe the kind-5 events publish a list of `e` tags each of which are to refer to a event `id` which should be considered to be deleted. This corrects language that refers to the event `pubkey` instead of the `id`.

Minor typos and a correction to NIP-09 reference to pubkey

---

README.md

Kind 6 was still in the README.md, pointing to the removed NIP-18...

removed kind 6 since NIP-18 has been removed from the spec

---

33.md

Going to merge this if it gets an approval, this behavior is already in the NIP. Also improves formatting.
See: 
> Upon a parameterized replaceable event with a newer timestamp than the currently known latest replaceable event with the same kind and **first `d` tag value** being received, the old event SHOULD be discarded and replaced with the newer event.  
The NIP *is* ambiguous, but the NIP also recommends using the `#d` tag to query + if I remember correctly while writing this I only intended the first parameter to be used so there is reason to believe this is the right implementation.

NIP-33: Add example for more than one value

---

01.md

The since and until filters does not clarify integer format and some relays fail to recognize filters with a float based timestamp.

Update NIP-01 to clarify since and until filters

---

50.md

Would be great if clients allowed searching for nostr posts/people by keyword.  Currently it's only possible if client starts using a non-standard third-party API. Adding this capability at nostr level, even if not many relays choose to support it, allows to a) avoid adding yet-another-way to fetch events, b) make API a standard, so that clients could switch.
Try wss://relay.nostr.band with `["REQ","1",{"keywords":["bitcoin"], "kinds":[1], "limit": 10}]`

NIP-50: Keywords Filter

---

26.md

This MR adds a section clarifying fields and operators supported when specifying condition strings for NIP-26, following the discussion [here](https://github.com/nostr-protocol/nips/pull/157).
We could potentially allow other conditions as well, however `kind` and `created_at` currently are the only I've specified here.

NIP-26: adding section documenting valid fields and operators for conditions string

---

19.md

the main purpose for this to be included as a `nostr:` URI.
some design choices:
- type `0` is reserved for relay since a relay type already exists (`1`)
- only one relay can be included in the encoded entity so that if metadata is added in the future there is no confusion on which relay it applies to.

Bech32 encoded relay entities

---

26.md

This MR fixes a typo found by @bhayward93 in the section explaining the conditions query string for NIP-26.
I wrote "delegator" here, but this should be "delegatee".

NIP-26: fixing typo in conditions query string section

---

26.md
README.md

The primary purpose of this PR is to advise delegators to precisely scope the time windows in their delegation token query strings, such that delegatees are not permitted to sign historic posts.
Additionally:
- Fixed a minor typo in the capitalization of Schnorr
- Extended the existing example to use the advice provided about scoping time windows.
- Fixed the example line (74) to indicate that you should be signing a ***SHA256 hash*** of the delegation token string.

NIP-26: Advice on using after operators in conditions query string

---

26.md

Multiple delegation conditions are implicitly `AND`  (`created_at` < X AND `created_at` > Y) so it's inconsistent to allow multiple separate `kind` conditions (e.g. `kind=0&kind=1&kind=3000`).
In my testing, relays reject delegation tokens with multiple `kind`s specified this way.
see: [`nostr-rs-relay`](https://github.com/scsibug/nostr-rs-relay/blob/4fd76439078b38a482083b7385601f05c145da97/src/delegation.rs#L170-L173)
When given `kind=0&kind=1&kind=3000`, the relay is enforcing that `kind` must equal 0. And then it requires that `kind` must also equal 1. And so on.
Relays DO accept `kind=0,1,3000` conditions:
https://snort.social/e/note132uwuffvahjns77plwggtjjf9ssttl7wjagzgkw0mcs0djp0cdwqqf6lm5
```
{
"id": "8ab8ee252cede5387bc1fb9085ca492c20b5ffce97502459cfde20f6c82fc35c",
"pubkey": …
```

[NIP-26] Fix for multiple `kind`s in delegation conditions

---

65.md
README.md

Gossip shouldn't have to be so complicated.  Nostr should scale better.  People should be able to find what they want.
This is related to nip-23 kind10001, except that that NIP is really more about people controlling what their clients do rather than to advertise to others, and has complex hard to code runes language stuff in it and has been sitting around for a long time now.
This is related to kind-3 contact list content, except that Contact Lists are far too long for this purpose and their content was also intended for users to control their own clients rather than to advertise to others.
So I thought a new kind was called for.

NIP-65 Relay List Metadata (was Feed Advertisements)

---

56.md
README.md

This NIP provides a way for clients to report profiles and notes to relays.
This is currently implemented by Damus as an apple app store requirement, but may be useful in other moderation contexts.
https://github.com/nostr-protocol/nips/blob/reporting/56.md

NIP-56: Reporting

---

01.md

Changed the wording to be consistent with other fields like "id" and "tag". It wasn' apparent to me that the signature was in hexadecimal when I read it the first time.

Added clarification for signature to be in hex

---

05.md

Proposing a couple of changes to the NIP-05 protocol to reduce the chance of fraudulent use of "verified" public keys.  At present, I could create an account on a well-known verifying server under a random name, and then send DMs pretending to be someone else, and there's no easy way for users to tell who the verifying account actually belongs to.
As well as displaying the name of the account on the verifying server, this PR suggests an enhancement to the JSON data being returned so that clients can redirect the user to the user's profile page on the server.  This will make it much easier for users to check that someone who claims to have verified their Nostr account is who they claim to be.

Nip 05 security proposal

---

04.md

Adds note on the differences between default behavior in libsecp256k1 and how it's done in nostr.

NIP-04: clarify how shared secret is computed

---

57.md
README.md

This NIP defines a new note type called a lightning zap of kind `9735`. These represent paid lightning invoice receipts sent by a lightning node called the `zapper`. We also define a another note type of kind `9734` which are `zap request` notes, which will be described in this document.
Having lightning receipts on nostr allows clients to display lightning payments from entities on the network. These can be used for fun or for spam deterrence.
https://github.com/nostr-protocol/nips/blob/zaps/57.md

NIP-57: Lightning Zaps

---

19.md
23.md
33.md
README.md

This one is much larger than I thought it would be. I lost my patience in the middle of it so the quality might have degraded.
This PR also modifies NIP-33 and NIP-19 to introduce a new canonical way of referring to parameterized replaceable events.

NIP-23: long-form content

---

26.md

Typo fix: the delegation token spec mentioned a hash of delegation _token_, correctly it is of the delegation _string_.

[NIP-26] Minor change to make delegation token/string naming consistent

---

19.md

The key pair in the example is derived from the secret recovery phrase:
`feel myself loan observe tragic prosper coral service evil fresh egg early`
The key is derived using the NIP-06 derivation path: `m/44'/1237'/0'/0/0`
Closes #255

Update the key examples with a key pair

---

57.md

This prevents an attack where a zap request note may be used for claiming a larger zap was done by the zapper than the zapper intended.

NIP-57: Add amount tag to zap request

---

57.md

Context: I'm building a NIP-23 reader/writer client and would be great to have zaps there. Since long-form content events are parameterized replaceable events the event id tipping makes it impossible to gather all zaps over time when an article has been updated.

NIP-57: add optional a tag for tipping nip-33 coordinates

---

04.md

Fix spelling of `coordinates` in Note

Fix minor typo

---

07.md

I believe this is current.
The linked Alby repo suggests that Safari is not supported, but their [macOS installer](https://github.com/getAlby/alby-installer-macos) suggests it is. I haven't verified.

Add browsers to the extension list

---

01.md

- "random" is not an accurate description
- I've noticed long (sha256 hashes in hex) being rejected by some relays. So there seems a need to specify a max length.
- "non empty", cause an empty string could be interpreted as `null` 
To be decided:
- Max length number
- Are `subscription_id`s case sensitive?
- Will `subscription_id`s be white space trimmed?

Improve `<subscription_id>` specification

---

46.md

After discussing with app developers, we decided to amend the spec of the methods of `describe` and `delegate` to improve the signatures of the methods to better serve implementers.
Already implemented in Nostrum

Amend nip46 describe and delegate methods

---

01.md

We mean to reference any public key. "the key" was a bit unspecific.

Update NIP-01 to clarify pubkey reference

---

04.md

The [`substr`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) method was never standard and is considered to be deprecated. Updated the code to use [`slice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) instead.

Avoid using `substr` in NIP-04 example

---

08.md

This addition addresses one part of #319, to address false-positive NIP-08 matches in viewing clients.
Although NIP-08 is declared `final`, I think this addition should go into NIP-08 itself, as it defines until now undefined behavior and intends to limit problematic use of NIP-08 where some clients take its application beyond current and intended specification.

NIP-08: Specify nonmatch behavior

---

28.md

NIP28 kind 42
Make explicit that root event tag is compulsory when replying to someone else's message

NIP28: Make explicit that root event tag is compulsory

---

04.md

I think "read" is misleading because the content is encrypted.

NIP-04: Minor wording change

---

04.md

The code sample assumed that a `Uint8Array` was actually a hex string.

NIP-04: fix bug in code sample

---

46.md

This change is made to be consistent with `window.nostr.signEvent` signature.

Amend NIP-46: Return full event with id and signature in sign_event

---

01.md

Often, a relay sends a `NOTICE` as a response to a `REQ` (such as rate-limiting, erroneous queries, etc); it would be useful if clients could associate a `NOTICE` to a previous `REQ`.

add optional subscription_id to NOTICE

---

01.md

fixed "the the serialized event data" => "the serialized event data"

remove tiny duplicate text

---

04.md

Example of mentions leaking: https://nostr.build/i/nostr.build_6866d14546b73b672add42180a6486cbfbff17d828359cdc7d49a10514d394ce.jpeg

Added NIP-04 metadata leak warning

---

06.md

I propose a change to NIP-06 that would allow the generation of infinite root keys by using the `account` field of the 5-level path used to derive Nostr keys under BIP32.
The current 5-level path used for NIP-06 is `m/44'/1237'/0'/0/0`, and only generates one private key. By changing it to `m/44'/1237'/<account>'/0/0`, we can generate multiple keys from a single parent bitcoin seed.

Add account_index for infinite NIP-06 key generation

---

README.md

Improvements to the `README.md` file.
Improvements include:
- added a Table of Contents to the file's top
- separated the kind ranges from the specific kind list
- added reference to NIP-33 to the note suggesting the reader to take heed of already defined kind ranges
- added all missing tags in approved NIPs
- tidied up tables
- minimal style changes to "unrecommended" notice
- ensured "one sentence per line" so as to minimize future diffs
:)

Improve README.md markdown

---

94.md

Currently, the `blurhash` property's description says 'cosmetic purposes'. This PR removes the vagueness in this description.

explain blurhash clearly in NIP-94

---

13.md

the example event id had 21 leading zeroes, not 20
I provided new C code that has been tested to work (my tests showed the example code to be incorrect) and I provided some JavaScript code to test event ids as well.
I did not re-compute the event id for the example event; I simply changed the nonce to be 21. Since it is an example, it may not matter that the event id is not the real event id for the updated event.
The thing that matters is that people understand how to correctly count leading zeroes without an incorrect example creating confusion.

example was incorrect

---

21.md

I think the `nostr:...` scheme is not actually a Uniform Resource Locator, because it doesn't tell you where the data is located. For instance if I see the string `nostr:npub1sn0wdenkukak0d9dfczzeacvhkrgz92ak56egt7vdgzn8pv2wfqqhrjdv9` I understand that this identifies a Nostr keypair but I don't know where to find data for that keypair. The scheme does fall under the definition of a Uniform Resource Identifier, or maybe even the stricter class Uniform Resource Name. But nobody talks about URNs, so maybe best to just use the less-specific term "URI" here.

Change NIP-21 URL->URI

---

45.md

Incorporates changes from https://github.com/nostr-protocol/nips/pull/503 and clarifies behavior.

Clarify how NIP 45 works with multiple COUNT filters.

---

01.md

I was a bit confused about the Markdown remark and had to read up https://github.com/nostr-protocol/nips/commit/379252f992c2528e287bc4ce7faee5631aa3f73c
I guess @fiatjaf did not want to forward reference, so I tried to keep both statements:
* No markdown by example
* Mentioning other event kinds
I added the interpretation that clients should not need to infer content in IE6 manner.

NIP-01 Rephrase Markdown special rule

---

28.md

The purposes of kind41 is to "update the kind40 metadata" without changing the "channel id" that is immutable.   kind41 events can replace each other, like kind33 replaceable events.   Only the most recent kind41 is needed.   We still need to keep the kind40 event, because it's the immutable event "id" and maintains the "owner" of the channel.
see issue https://github.com/nostr-protocol/nips/issues/376

Fix docs from kind0 to kind33

---

57.md

- Replaced `zap note` with `zap receipt`
- Fixed inconsistent quoting of `zap request` & `zap receipt` (quoted all occurrences of them)
- Fixed description about the `nostr` query parameter in the Appendix D
- "the contents of the event" would be misread as "the `content` field of the event", though the `nostr` query param includes the whole event.

Minor Fixes of NIP-57

---

30.md
README.md

Adds a NIP for custom emoji, similar to Mastodon. It is [already implemented by the Mostr bridge](https://gitlab.com/soapbox-pub/mostr/-/merge_requests/56).
A real-world event can be found here: https://www.nostr.guru/e/5e1e0e524432e524f9584f296f72dda5559fc9fe6116a744baa43ea6769c7b65

NIP-30: Custom Emoji

---

07.md

Currently Alby does not support Safari.
https://github.com/getAlby/lightning-browser-extension#browser-support
> Alby supports
> - All Chromium based browsers - Chrome, Edge, Opera, Brave etc.
> - Firefox
> - more coming soon...

Fix Alby description in NIP-07

---

16.md
33.md

- This is so that relays can converge on a deterministic sets of events, no matter the order they were received
- Otherwise, clients or relays that sync their sets of events could continually retransmit events they think are missing on the other side, wasting bandwidth

Specify replacement behaviour when replaceable events have the same timestamp

---

26.md

In the current form of the NIP, there is no recommendation against infinite duration delegated keys. If a user were to create a delegated key with no end timestamp (or one very far in the future) it would be granting similar permissions in most cases to the root key and providing very little real-word security improvement.
While it's hard to come up with a recommended timeframe as it's a personal decision, we *should* recommend people at least include an ending timestamp for the delegation so it will be unusable at some point if compromised.

Add context for limiting `before` timestamp

---

18.md

Solving https://github.com/nostr-protocol/nips/pull/576.

Kind 16 generic reposts

---

32.md
36.md
56.md
README.md

Supersedes https://github.com/nostr-protocol/nips/pull/524
Content moderation involves labeling content. In https://github.com/nostr-protocol/nips/pull/459, @gruruya proposed expanding NIP-56 to encompass labeling. I chose to create a new NIP rather than update NIP 56 because backwards compatibility would have been difficult to maintain, and because the purpose of the NIPs are slightly different (see below).
In https://github.com/nostr-protocol/nips/pull/457, @s3x-jay and @rabble proposed a nomenclature and more comprehensive mechanism for content reporting/labeling. The consensus seems to be that a nomenclature is not a good idea, but there were some good ideas to include.
In https://github.com/nostr-protocol/nips/issues/522#issuecomment-1546286149 I realized that the same labeling …

Add NIP-32 for labeling things in nostr

---

01.md

Minor edit, for clarification: The time unit for all date attributes in the filters (since, until) is in seconds.

Minor edit: specify the unit of the filters' date attributes (seconds)

---

README.md

I think the value column is better for the image URL of emoji tag, because the meaning of "other parameters" is ambiguous.

Update tag list

---

01.md

I think it would be better to have it clearly stated to avoid confusion for new readers.
What do you think? And let me know if you have a better wording.

NIP-01: Explicitly state that the `subscription_id` is treated per connection

---

01.md

Discussions of the particular decision to standardize `since <= created_at <= until` (closed interval) is in #650.
Resolves #650

NIP-01: add detailed description of since/until in filters

---

402.md
99.md
README.md

This adds a new new event `kind:30402` for generic classifieds.
An implementation of a Nostr job board using this new event: https://ostrich.work/

NIP 99: Classified Listings 

---

README.md

The nostr ecosystem is getting large with many different organizations, relays and clients. Following the nips repo on github is becoming more difficult and noisy. To coordinate on protocol development outside of github, I've added some links to nostr mailing lists. Also not depending on github is a plus on its own.

Add mailing lists to readme

---

01.md

From reading #579, #663 and the implementation of major relays, it seems that the descending order of the `created_at` is a common understanding, so this PR clarified it.

Clarify sort order when specified limit

---

48.md
README.md

This NIP provides a standardized way to tag events from ActivityPub, Bluesky, etc so clients can link to them on their original protocol if they wish. On the Mostr bridge this will allow me to stop using the custom `mostr` tag and instead do it in a more standardized way.
:arrow_right: Read link: https://github.com/alexgleason/nips/blob/proxy/48.md
(This proposal is inspired by [FEP-fffd: Proxy Objects](https://codeberg.org/fediverse/fep/src/branch/main/fep/fffd/fep-fffd.md))

NIP-48: Proxy Tags

---

172.md

The goal of this NIP is to create moderator-approved public communities around a topic and provide a simple solution to Reddit clients that might want to come into Nostr. 
Let the best curators win. 
Read it [here](https://github.com/vitorpamplona/nips/blob/moderated-communities/172.md)

NIP-172: Moderated communities

---

51.md
README.md

In order to standardize the new kind `30303`used in the nostree client, the content of nip 51 is extended to include the new kind and its definition. It is not really a big change in the nip, as I have tried to follow the previous standards. I hope I have expressed it as well as possible and would appreciate any feedback. 
Cheers

Nip 51 extended kind 30001

---

315.md
README.md

This NIP enables a way for users to share live statuses such as what music they are listening to, as well as what they are currently doing: work, play, out of office, etc.
[315.md](https://github.com/jb55/nips/blob/user-statuses/315.md)

NIP-315: User Statuses

---

75.md
README.md

Introduces a new event kind for fundraising goals using zaps. Users can contribute funds towards the goal by zapping the goal event.
Read: https://github.com/nostr-protocol/nips/blob/goals/75.md
- [Goals](https://goals-silk.vercel.app/) ([source code](https://git.v0l.io/verbiricha/goals))
- [Zap.stream](https://zap.stream) ([source code](https://git.v0l.io/Kieran/stream))
- [Snort](https://snort.social) ([source code](https://git.v0l.io/Kieran/snort))

NIP-75: Zap Goals

---

94.md

Clarifying case sensitivity is useful for filtering events.
I think this change does not negatively impact existing implementations using `m` tag.

Clarify character case of m tag value

---

24.md

Because Nostr won't survive if all clients have to keep checking for `displayName`, `handle`, `username` and whatever else is in there.
https://github.com/nostr-protocol/nips/blob/extra/24.md
Motivation: https://njump.me/nevent1qqs9pt0ghyzzq7p6pqajnlvjgr7n9tyhy0vhpuyhgvdrd6y5r50n90cppemhxue69uhkummn9ekx7mp0qyghwumn8ghj7mn0wd68ytnhd9hx2tcar0mnt

add nip-24: extra metadata fields

---

94.md

Updated NIP [here](https://github.com/arthurfranca/nips/blob/94-tags/94.md)
`preview` for thumbnails or preview text
`caption` for a loose description (as nip94 `content` is currently being used by Amethyst as alt text for accessibility)
The `caption` makes it possible to use nip94 in a media gallery without using another kind (using a `t` tag to differentiate the event from a non-media-gallery one).

Add preview and caption tags to nip94

---

65.md

This is intended to address the issue of some clients duplicating connections due to trailing slashes in the relay URI.

65: trim trailing slashes from relay URIs

---

57.md

@verbiricha [reached out letting us know SN's zapper wasn't including `a` tags in the zap receipt.](https://snort.social/e/nevent1qqsx2gxs8e6jk9mzwvwyuw6u2y863acewy2pqg0dn5hhzqed4rxj0asu7e8e8)
Figured it should be added to the spec for future zappers.

update nip-57 zap receipt spec to include 'a' tag

---

25.md
README.md

- Define "generic reactions" (`kind 17`) in the same way as "generic reposts" (`kind 16`)
- #610
- Any clients reacting only to `kind 1` events will not need additional support, and clients reacting to events other than `kind 1` events will be able to handle the kind they want.
I am developing a client for Public Chat ([NIP-28](28.md)) that can react to `kind 42` events.  
However, it is causing troubles for other clients that only handle `kind 1` events.  
In addition, I only want to handle reactions to `kind 42` events.  
So I want to use generic reactions containing the `k` tag.

Change wording to imply that reactions can target any event

---

06.md

Add test vectors for deriving from mnemonic seed words (12 and 24). This should be triple checked before merging!
Possible changes / additions:
- Markdown layout
- mnemonic + passphrase vector
- account > 0 vector

Nip 06 test vectors

---

32.md

I added label annotations to NIP 32 in order to support reviews as a use case. This was a mistake for the following reasons:
- It adds a 4th positional argument, which is too many
- That argument is json-encoded and therefore way too open-ended
- The suggested keys for the json object were poorly defined (especially context)
Most importantly, giving labels a `value` field transforms labels into a key-value store. This makes this NIP applicable to many more use cases (like reviews), but is a very poor fit for them. Adding a regular tag to the even can cover many of them orthogonal to NIP 32. For the rest, a different data structure should be used.
For those of you wondering why I left the `L` tag in and mandatory, they're important for the following reasons:
- `L` tags make it possible to …

Remove label annotations from NIP 32

---

90.md

We are not able to implement NIP-90 without encrypting the generative AI parameters and results. Currently the users are using kind 4 event to communicate with AI agents. This is not useful since kind 4 events are not visible within the DVM eco system. The change requested follows the same logic as NIP-51 where the private lists are encrypted and stored on the content field. 
link to changes: https://github.com/starbackr-dev/nips/blob/patch-2/90.md

Adding encryption NIP-90 Data Vending Machine

---

32.md

This is a follow up from #872. It doesn't change anything, it only attempts to clarify the NIP text since there is a lot of confusion about it.
One common source of confusion is the existence of values in labels. I wouldn't mind seeing RDF triples being supported by nostr at some point, but they have a number of problems:
- Labels are completely different semantically from triples. Combining both in a single NIP is probably not a good idea.
- There is no way to search arbitrary key/value pairs, since nostr only indexes single-letter tags, and only their first argument.
RDF triples weren't the goal of this NIP, so it should be left to another PR (either to this NIP or a new one) to support them.
@s3x-jay @sroertgen @rodant

Clarify NIP 32

---

README.md

Adds a cool viz with all contributors to the readme. 
Check it out at the end of the readme here: https://github.com/vitorpamplona/nips/tree/contrib
Related: 
- https://github.com/nostr-protocol/nips/issues/162
- https://github.com/nostr-protocol/nips/pull/883

Adds contributor images to the readme.

---

11.md

Because relays may have other kinds of arbitrary restrictions that are not `payment_required`.

NIP-11: add `"restricted_writes"` limitation

---

51.md
README.md

https://github.com/nostr-protocol/nips/blob/save-nip-51/51.md
This NIP was a mess and wasn't being followed and there were many wild standards not documented. We should try to agree and actually follow some standards.
Also I've simplified the format to display some clearly defined simple tables so it's easier for people to add more stuff here.
We should stick to the 1xxxx range going forward for lists with standard meaning for which users are only expected to have one, 30001 for random lists and new 3xxxx lists for lists with standard meaning for which users are expected to have more than one.
---
**Update:**
This actually turned out to be a big movement involving tons of client developers in rehabilitating NIP-51, writing down old standards, creating new ones and cleaning up some mess …

Make NIP-51 useful again

---

58.md

This paragraph may have been valid in an earlier iteration of the Badges NIP, but IMO it's not the case anymore, so this PR removes it.
My reasoning is as follows:
- PoW cannot be used for Badge Definitions to imbue value to the Badge, because the Badge Definition is a parametrized replaceable event. This means one version of it could have some PoW, but the event can be edited and replaced, thus losing the PoW. So any difficulty bits here are only temporary and cannot be used as an enduring property of the Badge. A collector would feel rugged if they got a high-PoW badge, then later it was edited and the badge lost the difficulty bits.
- Similarly, it makes little sense to rely on PoW in the Badge Awards to signify a higher value of the Badge. It's not the awarding that people value, but …

Update NIP58 Badges: Remove section on PoW

---

01.md
42.md
45.md
README.md

I will quote my own message from https://github.com/nostr-protocol/nips/pull/841#issuecomment-1828345933 to explain this:
> Basically we have two distinct problems:
> 
> 1. knowing why a relay is asking for `AUTH`
> 2. knowing why a subscription has failed
> 
> adding a third element to `AUTH` only solves them in the occasion that the two happen together.
> 
> creating a new message solves 2 and making `AUTH` be subservient to that (and also to `OK`) solves 1.
More relevant messages were posted to that other thread but should probably have been posted to this.

`CLOSED` messages for relays that want to reject REQs and NIP-42 `AUTH` integration

---

README.md

It's now the second time that I searched for what's the matter with kind `2`.
Kind `2` was [consciously](https://github.com/nostr-protocol/nips/pull/703#issuecomment-1672098794) removed in https://github.com/nostr-protocol/nips/commit/72bb8a128b2d7d3c2c654644cd68d0d0fe58a3b1#diff-39307f1617417657ee9874be314f13aabdc74401b124d0afe8217f2919c9c7d8L105.
Mentioning the fact in the event kinds table should help prevent further confusion.

Mention deprecation of kind 2 in README

---

44.md

- Clarify separation of concerns (encryption vs messaging)
- Improve formatting
- Clarify encryption/decryption steps
- Re-order sections to be more welcoming to less technical readers
- Clarify that this is not a drop in replacement for NIP 04
One thing to note is I took out the language about putting an encrypted payload into `content` specifically, since an encrypted payload could also be placed in `tags` (probably a bad idea in practice, but up to other NIPs to specify). The important thing is that the payload is part of the event's hash and authenticated by its signature.

Clean up NIP 44

---

01.md

As mentioned further down in NIP-01
> A REQ message may contain multiple filters.
The comma makes it more clear that the message array can container more than 3 items. So it is understood easily to match
```
// correct:
["REQ", <subscription_id>, filters1, filters2, …]
```
instead of 
```
// wrong:
["REQ", <subscription_id>, [filters1, filters2, …]]
```

Emphasis on multiple filters in NIP-01

---

01.md

Rephrase to "MUST" so that one does not assume a connection could `CLOSE` any `subscription_id`, which it must not. Otherwise one could close other people's subscriptions.

NIP-01 Tighten-up subscription_id management rule

---

07.md

I think the list of implementations is unnecessary as the specification, so I replaced by link to awesome-nostr instead to keep the document simple. awesome-nostr lists more implementations.

Simplify list of NIP-07 implementations

---

94.md

1. No one seems to be using it. 
2. People who wish to use encryption can now use the new NIP-44 scheme.
3. The existence of the tag as is creates more questions than solutions.

Removes the `aes-256-gcm` tag from NIP-94

---

57.md

A lot of blood has been shed by the lack of an index to find zaps sent by a pubkey.
Mutiny wallet is running a primal index server just to be able to run this simple query.
CHILDREN ARE DYING!

index zap senders with P tag

---

96.md

[NIP-54: Inline Resource Metadata](https://github.com/nostr-protocol/nips/pull/521) is not merged yet.

Remove NIP-54 mention temporarily

---

01.md

"#p — a list of event pubkeys" - this sounds wrong. Events don't have pubkeys!

#p refers to pubkeys, *not* "event pubkeys".

---

30.md

Custom emoji is also used in `kind 7` (Reactions) and `kind 30315` (User Statuses).

NIP-30: add supported kinds

---

47.md

Have gotten requests for things like this from various users. This handles the receive side of nostr wallet connect

NIP-47: Nostr Wallet Connect Extensions

---

59.md

A modified version of #468 focused on the wrapping standard, and omitting DM-specific stuff. @v0l please feel free to incorporate this diff into the original PR and I can close this one, or close the original and we can continue from here, it's up to you.

Introduce NIP-59 gift wrap

---

49.md

In NIP-49, the words PASSPHRASE and PASSWORD both existed to mean the same thing. 
After checking the scrypt documentation, password seemed to be correct.
FYI. https://nodejs.org/api/crypto.html#cryptoscryptpassword-salt-keylen-options-callback
So I unified the words into password.

NIP-49: Fix correct PASSPHRASE to PASSWORD

---

29.md
94.md

This is adapted from Damus' DIPS repo: https://github.com/damus-io/dips/blob/master/01.md. I don't love the format, but I think there are probably a good number of events in the wild already using it. This PR is backwards-compatible except for renaming sha256 to x following NIP 94.
@jb55 correct me if I'm wrong and there is an opportunity to revisit the format. My preference would be to make the `url` the first argument of the tag rather than the value of the `url` key to make it more conventional. It would also be nice to use a query string or json or something instead of space delimited data.

Add imeta tag

---

29.md
README.md

This improves the intro of NIP-29 a little more, and adds a missing `m` (mime) value to the example event.

NIP-29: add to NIPs list, improve preamble phrasing

---

39.md

I thought it would make sense to add PGP here as it is an external identity, but open to move it somewhere else
Should the full PGP public key be included as well?

Add PGP as NIP-39 external identity

---

49.md

This will aid compatibility.
Shocking for me to suggest a breaking change after my hissy fit last night. But I'm actually ok with important breaking changes as long as we document them (see my other PR here https://github.com/nostr-protocol/nips/pull/1052).

NIP-49 [breaking]: password normalized to unicode NFKC format

---

46.md

I recently implemented the current version of NIP-46 in [nostr-ignition](https://github.com/erskingardner/nostr-ignition) and found it very painful. After talking to several other folks that have also implemented this NIP and found it painful, I decided to try and improve the NIP to make it more likely that remote signing is adopted by more of Nostr.
My proposal changes NIP-46 significantly based on a few principles. 
* Use separate event kinds instead of JSON-RPC style payloads with methods.
* Simplify payloads as much as possible, only using objects or arrays where absolutely necessary.
* Use NIP-44 encryption for payloads instead of NIP-04
I've talked to quite a few folks over the last few weeks on this so thanks for all the input @fiatjaf, @pablof7z, @staab, @nostrband, and others. 
I …

New version of NIP-46

---

07.md

Very simpler alternative to #940
It does the same thing as NIP-04 but with the better encryption.

NIP-07: add NIP-44 calls

---

46.md
49.md
65.md

NIP-46, NIP-49, NIP-65: fix typos

---

18.md

Damus does this, other clients should too!

Use `q` instead of `e` tags for quote reposts

---

34.md

The simplest possible git collaboration flow that has a chance of working.
The patch stuff is based on http://git.jb55.com/git-nostr-tools, with some changes.
https://github.com/nostr-protocol/nips/blob/git/34.md
Here's a standalone CLI tool that allows for announcing a repository, sending and downloading patches: https://github.com/fiatjaf/gitstr -- probably very rough still, but I just merged a patch from myself using it so I am happy.

NIP-34: git stuff

---

50.md

As previously discussed in the other NIP-50 PR with @alexgleason and @fiatjaf...
We have recently started experimenting with event classification (https://docs.nostr.wine/api/classification) on our nostr.wine relay. 
I've added language, sentiment, and nsfw to extensions. I also updated the wording of the domain: extension to include ONLY events from users instead of just "include events". Let me know if I'm misunderstanding that.
I'm not sure of the best format for everything (is ISO 639-1 a good choice for language codes?) but wanted to get something started.

NIP-50: add event classification extensions

---

88.md

- A kind 37001 dtag is referenced in the 7003 description, but was missing in the example
- An  e tag is referenced in the  kind 7001 description but an a tag was referenced in the example. I think e tag would be correct

Nip88: Adding dtag, 7001 etag

---

24.md

This is an extension of the Kind 0 fields, to allow profiles to self-indicate if they are a bot.
There are an increasing number of automated npubs that are simply newsfeeds or cross-posting from other places, such as RSS or Twitter. This is completely legitimate and many users find them helpful, to consolidate their various reading lists, but it creates confusion when there are two npubs with the same name (one human, one automated), or when people try to respond to these bots, as if they were humans.
There are also an increasing number of chatbots, infobots, DVMs, etc. that could make their status more clear to users and clients.
Until now, profiles denote this status in freetext descriptions, but that makes it difficult to query or filter, and limits the ability to easily create clients …

Added bot field to denote automated npubs

---

28.md

Choosing relays for NIP-28 has been quite a challenge. With these changes, the owner of the chat can recommend relays in the metadata events.

Clarifies relays to be used for NIP-28

---

BREAKING.md

NIP-46 goes on the list of shame again.

Update BREAKING.md for NIP-46 (stringified params)

---

56.md

This adds an `other` category alongside the 5 others listed in this NIP. At Nos we add NIP-32 labels to our reports so we often have users publishing reports for things that don't fall into the five buckets listed in this NIP (nudity, profanity, illegal, spam, impersonation). For example, if I report a note from Nos that shows nsfw gore what should we put in the `report type`? Other apps like Amethyst will show this report using only the `report type` so we don't want it to be wrong. Hence the need for an `other` category.
This is something we've been using in production for over 6 months now, I imagine other apps will/do want this, and we would like to see support for it in some of the libraries we use (like [this](https://github.com/rust-nostr/nostr/blob/bef044f5fed68256393094568219d1aa8 …

Add `other` category to reports

---

56.md

This makes a couple changes to NIP-56 reports to more closely align with how they are being used in production. I know the origins of the NIP are tounge-in-cheek, but it's seeing some real use now which warrants some updates.
I removed the `draft` label from this NIP since it's has been in use for over a year now, and multiple apps (at least Nos and Amethyst) have built moderation systems on top of it.
I rewrote the description at the top to add more detail ("a report is... used to report" struck me as redundant) especially in light of NIP-32 labels which are very similar structurally. When should you use a report instead of a label? I think it's when the content is objectionable. 
I also added some words about the subjective nature of moderation to help distance Nostr reports from …

Update description of NIP-56

---

46.md

It's very confusing as to whether `<remote-pubkey>` refers to remote user pubkey vs remote signer pubkey. This is complicated further by the typo in the explanation of "remote signer pubkey", which makes it hard to infer which would be used. Can we just be explicit here?

NIP-46 : Fix use of confusing ambiguous term

---

46.md

The `error` property of NIP-46 responses is optional.
nsecbunker [marks it optional](https://github.com/nostr-dev-kit/ndk/blob/44ab157ccf46297700a7b159d5343bcd31536e8a/ndk/src/signers/nip46/rpc.ts#L26) and only returns it [conditionally](https://github.com/nostr-dev-kit/ndk/blob/44ab157ccf46297700a7b159d5343bcd31536e8a/ndk/src/signers/nip46/rpc.ts#L103) if an error exists.

NIP-46: "error" property of response is optional

---

46.md

This is how it works on NIP-07 and should be how it works on NIP-46 too.

nip46: signer should fill in `pubkey`, `id` and `sig` on `sign_event`

---

56.md

A report is a kind 1984 event that signals to users and relays that some referenced content is objectionable. The definition of objectionable is obviously subjective and all agents on the network (users, apps, relays, etc.) may consume and take action on them as they see fit.
The content MAY contain additional information submitted by the entity reporting the content.
Currently there is Nip 56. But can we include more use cases? Can we include specific tags such as malware(virus, trojan horse, worm, robot, spyware, adware, back door, ransomware, rootkit, kidnapper, etc)?
I explained this technical detail here https://gist.github.com/lucasnuic/cf71109d0760542ad7ad2f2d2c260c44 , https://github.com/nostr-protocol/nips/discussions/1212

NIP-56 to reporting of digital threats

---

25.md

Current guidance recommends including all `e` tags and `p` tags, but no other tags, from the liked post in the reaction event. I believe this is a relic of the past and should be deprecated. 
There is no need to index the entire thread in every single reaction. The indexing burden in popular threads is real. I would argue reactions should only point to the note receiving the reaction and nothing else. 
Reasons for the change: 
1. Indexing burden: Indexing entire threads for every single reaction has quadratic costs on the thread's popularity. 
2. Data consumption: requesting reactions to posts in the feed downloads all reactions to all replies in that thread, which is not necessary. 
3. No consistency: We now use NIP-10 markers instead of positional `e` tags for the entire thread. This …

Changes reactions to not include the entire thread as e-tags. 

---

47.md

The format in the example given doesn't work with any of the Alby NWC tools.

NIP-47: fix NWC connection string example

---

10.md

I have found that sometimes relay hints are not enough, and it would be much easier to find replies in a thread if that thread added the pubkey of the author as an additional argument to the `e` tag

NIP-10: pubkey arg

---

35.md
README.md

Making a NIP for torrents with a few updates
read: https://github.com/nostr-protocol/nips/blob/feat/nip35/35.md

NIP-35: Torrents

---

13.md

I'm reverting a change made by @arkin0x in commit: https://github.com/nostr-protocol/nips/commit/6fb9e54f7b4886272f7464aba2f0971543d8df40#diff-cb504c91ef546f76741fb8fd4c13b1f97e4b5ce2a9d78afa545fb6ec799e06c2L39 which renders the example event unverifiable because of a changed hash.
Please compare:
```python
import hashlib
import json
pubkey = "a48380f4cfcc1ad5378294fcac36439770f9c878dd880ffa94bb74ea54a6f243"
created_at = 1651794653
kind = 1
tags = [
[
"nonce",
"776797",
"20"
]
]
content = "It's just me mining my own business"
pre_event = [
0,
pubkey,
created_at,
kind,
tags,
content
]
serialized_event = json.dumps(pre_event, separators=(',', ':')) 
print(serialized_event)
event_hash = hashlib.sha256(serialized_event.encode('utf-8')).digest()
event_id = …
```

NIP-13: Fix of otherwise unverifiable example event

---

01.md

When someone new wants to learn about Nostr, most probably this person will start reading by order starting with NIP-01, therefore it is good to keep some NIP utilities mentioned so the user can figure it out about them in a fluid way, without having to be inspecting all the NIPs list.

Mention extra metadata fields may be set

---

71.md

For the same reason as #948.
> 1. No one seems to be using it.
> 2. People who wish to use encryption can now use the new NIP-44 scheme.
> 3. The existence of the tag as is creates more questions than solutions.

NIP-71: remove `aes-256-gcm` tag

---

96.md

A continuation of #1236 
@fishcakeday @nostrband @quentintaranpino

NIP-96: no transform

---

README.md

This PR clarifies the "client implementation" requirement. With NUDs, this will no longer really matter, but in the meantime I think it's important to be clear that adding render support for a kind to a popular client does not constitute "implementation".

Raise bar for NIP implementation

---

96.md

Adding an endpoint to list uploads
Also included a bit of rewording, this NIP is far too long.
read: https://github.com/nostr-protocol/nips/blob/nip96-sync/96.md

NIP-96: List files / rewording, no_transform

---

50.md

Searching for `fiatjaf` right now brings back the `n` most recent metadata changes. If clients limit by 100
```
["REQ", "mysub", {"kinds":[0],"limit":100,"search":"fiatjaf"}]
```
The results don't include @fiatjaf. 
Either NIP-50 relays are returning based on `.created_at` OR the scoring algorithm is not very good.
Pinging NIP-50 operators: @nostrband @nostr-wine @Semisol

Adds Order of results for NIP-50 Search

---

32.md

`l` tags are really useful as a general-purpose indexable value. Adding `L` in many cases doesn't really help anything, and is quite ugly. Use cases:
- Language: `["l", "en-US"]`
- Indexing 31337 creator: `["l", "Ainsley Costello"]`

relax requirements for NIP 32 L tags

---

57.md

The `description` tag includes the 9734 zap request event, writing "_JSON-encoded invoice description_" as it is seems confusing.

NIP-57: Clarify description tag

---

09.md

Deleting a replaceable event is not well defined. It should delete all versions of the event up to the created_at timestamp of the deletion event itself, to allow the author to publish that kind of event in the future.

NIP-09: clarify "a" tag deletions

---

01.md
05.md
README.md

This is not a correction but a suggestion...
When I first read it, it wasn't clear that metadata is specifically for a user and not inclusive of other things (eg not metadata about a photo).
Adding this one extra word here would have helped me understand that immediately.

metadata clarity.md

---

01.md

When trying to learn about the protocol I got confused as to wether or not kind 1, 2, 4 up to (and including) 44 are regular lifetime or not. After some asking around it seems that they do, please correct me if i'm wrong.

Clarify which kinds have lifetime of 'regular' 

---

01.md

Lower in this document, this is expressed as "since <= created_at <= until".
But the English description said that these values had to be "newer than" or "older than".
These two were in conflict. I assume the inclusive behavior is the intended one, since that documentation was added later to clarify. This just makes both cases match.

More precisely document since/until bounds.

---

70.md

Read about it in the NIP body: https://github.com/nostr-protocol/nips/blob/protected-events-tag/70.md
This is inspired by https://github.com/nostr-protocol/nips/pull/1029, there is more discussion there.

relay-based event access-control with the `["-"]` tag

---

39.md

The text `in addition to the name, about, and picture fields` confuses implementers about where the `i` tag should be placed. This can be interpreted as a `"tags"` field should be in a JSON in `"content"` of `kind:0`.
```
A new optional `i` tag is introduced for `kind 0` metadata event contents in addition to name, about, picture fields as included in [NIP-01](https://github.com/nostr-protocol/nips/blob/master/01.md):
```
However, `i` tag should be in `tags` directly under the root of event actually.
This PR clarify that `i` tags should be in `"tags"` field directly under the root.
I checked the background of this NIP, I found that `i` tag should be in `"tags"` directly under the root.
In the very initial version of this NIP, identities was in `"content"` JSON. …

NIP-39: clarify that i tag should be in tags

---

46.md

Not sure whether I phrased it unambiguously enough and correctly in terms of this NIP, feel free to make any changes.

Fix #1377: NIP-46: It's not obvious to the end-user that optional secrets are not temporary

---

01.md

See discussion in https://github.com/nbd-wtf/nostr-tools/pull/398
It's a small detail, but can matter a lot for syncing relays, pagination, and ultimately UX.
The order is: `created_by DESC, id ASC`

NIP-01: sort events by id after created_at

---

19.md

It's better to just use relay hostnames or full URLs, more readable. This encoding just adds unnecessary bloat and confusion and obfuscates things. Is anyone using it? I know @verbiricha's https://nostrrr.com/ has support for it, but now it has transitioned to using hostnames primarily, which is much better.

nip19: remove `nrelay`

---

32.md

The language in the introductory paragraph is misleading. 
```
A label is a `kind 1985` event that is used to label other entities.
``` 
Is not an accurate statement, particularly as the opening sentence. The definition is out of order when it comes to communicating the purpose of the NIP. 
As written, it requires an implementer to read the entire NIP before it is communicated that `l` and `L` tags may be applied to any event. 
If summarizing NIP-32 in its entirety: 
```
A label is two new indexable tags used label events. It additionally adds an event kind used for labeling other events. 
```
See changes for actual language used.

NIP-32: Clarify Language in summary

---

45.md
README.md

- No non-defunct relay implementations that I'm aware of
- No active client implementations that I'm aware of (coracle has some code but doesn't use it)
- There's no way to accurately reconcile counts between multiple relays
- Increases complexity of relay implementations
- Better handled outside relays (via centralized service or DVM)
- I was the original author of COUNT

Remove NIP 45 COUNT

---

34.md

so that the event can be used as a source of truth for the state of refs such as branches and tags.
this could be useful as:
1. a way to reduce trust in git server.(s) so they no longer act as a source of truth.  A nip34 git remote-helper could proxy requests to git servers and only pull updates when they match the state listed in the repo event.
2. a form of authorisation for nip34 git server implementations such as song
3. a way of enabling experimentation with other protocols for hosting and accessing git data. eg a blossom git remote helper

nip34: add refs to git repo event

---

45.md

remove nip45 code block type and then code will not highlight error.
before changed:
after changed:

remove nip45 code block type

---

52.md

Cornychat.com relies on a `t` tag of `audiospace` for filtering.  Flockstr.com relies on optional and previously undocumented `audio` and `image` tags for rendering.

Add used fields to Calendar Time Event in NIP-52

---

64.md
README.md

NIP-64
======
Reserving `kind := 64` for notes representing chess games in[ PGN format](https://en.wikipedia.org/wiki/Portable_Game_Notation).
NIP-64: https://github.com/theborakompanioni/nips/blob/nip-64/64.md
Website: https://jesterui.github.io/nip64/
(Former discussion: https://github.com/nostr-protocol/nips/pull/212)

NIP-64: Chess (Portable Game Notation)

---

README.md

README: add NIP-52 link to `image` and `summary` tags

---

09.md
32.md
34.md
71.md
72.md
90.md
README.md

There's endless debates about whether or not Nostr supports deletion, but I think the confusion stems from overloading the term "delete". In actuality, Nostr supports "request for deletion", but it's a mouthful and can still be confused with just plain "deletion".
Let's call it "retraction" when we mean a request for deletion, and reserve "deletion" when we actually mean delete.

Update NIP-09 to rename to deletion request

---

54.md

== Why?
Because Markdown is somewhat of a mess. It's fine when you just use the core features, but when you start to add tables and other stuff it quickly degrades. And there had been talks already of how to add description lists, footnotes, sidebars and tables to these wiki articles so we would not be able to stick to mostly plain text anyway.
Asciidoc has a strict spec, multiple implementations in many languages, and support for features that are very much necessary in a wiki article, like _sidebars_, _tables_ (with rich markup inside cells), many levels of _headings_, _footnotes_, _superscript_ and _subscript_ markup and _description lists_. It is also arguably easier to read in its plaintext format than Markdown.
Read this if you're still not convinced: …

nip54: change to asciidoc

---

51.md

Fix #1156
```json
{
"kind": 30007,
"content": "<encrypted tags>",
"tags": [
["d", "<kind>"],
["p", "<pubkey 1>"],
["p", "<pubkey 2>"]
]
}
```

Kind mute sets

---

01.md

Fixes https://github.com/nostr-protocol/nips/issues/1332

Clarify what happens when a duplicate subscription is sent, remove CLOSED on duplicate subscription

---

09.md
10.md
11.md
26.md
32.md
35.md
38.md
44.md
45.md
46.md
55.md
64.md
71.md
73.md
96.md

Some NIP headers were different from others. I just changed their style to the same format. That's not bad to take care of their format in reviews when someone changes them.

style: fix header styles in same format

---

118.md

This NIP takes the ideas evolved from 
- https://github.com/nostr-protocol/nips/pull/1190
- https://github.com/nostr-protocol/nips/pull/1324
- https://github.com/vitorpamplona/amethyst/issues/935
- https://github.com/nostr-protocol/nips/pull/320
- https://github.com/nostr-protocol/nips/pull/148
and tries to combine them in a spec for a  simple polls implementation. 
Working version: https://pollerama.fun/
cc: @staab @vitorpamplona @vicariousdrama @alexgleason @gocedoko  @fiatjaf

NIP-118, Polls on Nostr 

---

88.md

Follow up to https://github.com/nostr-protocol/nips/pull/1346
Change kind 1018 to 30068.
We already have existing code, relays, systems etc that apply the right semantics for replacing an event, so we should use that, otherwise people will have to do a lot of extra work to add special support for polls.

NIP-88: make poll response a parameterized replaceable event

---

65.md

To be honest, [this](https://github.com/nostr-protocol/nips/pull/1459#issuecomment-2322563148) was one of the concerns. This PR will resolve it.

NIP-65: add link to outbox model article

---

73.md

Following on from the discussion around adding a [Generic Comment NIP](https://github.com/nostr-protocol/nips/pull/1233) - this PR adds the extensions to the `i` tags that are supported in the Generic Comment kind `1111`.
This PR is optional depending on whether the list of supported external content ids should be in it's own NIP or part of the Generic Comment NIP.

NIP-73 - Expand External Content IDs

---

55.md

1. Change some fields ```pubKey``` to ```pubkey```, just other nips does.
2. When transmitting information, other nips use pubkey, but here npub is used, and npub is changed to pubkey.
3. Add a function ```get_relays``` just like other nostr signer [NIP-07](https://github.com/nostr-protocol/nips/blob/master/07.md) and [NIP-46](https://github.com/nostr-protocol/nips/blob/master/46.md)
You can see the detail from this [link](https://github.com/haorendashu/nips/blob/nip55-fix/55.md) .

fix some info of nip55 to be same as other nips

---

18.md

This change is fairly opinionated in terms of dictating best practices. I'm also not sure if address support is desired/implemented anywhere, so I'm happy to take that out if appropriate.
The diff is kind of hard to read because I moved the quote reposts section to the bottom of the NIP for better readability.

Clarify quote reposts

---

55.md

This changes the return field from signature to result
Returning signature can confuse people since it only returns the signature if it's a sign_event

[NIP-55] - Change return field from signature to result

---

18.md

If a `naddr` is added to a note's content, it should be referred to in the tags. But using an `a` tag will cause the quote to be treated as a reply (as used to happen with events). In some cases, using a `q` tag with the event's id rather than address may work, but it goes against user intention, and it may not always be possible to convert an address to an id if the event is not loaded by the client. Adding an address variant to `q` tags fixes this.
Related conversation: https://github.com/cesardeazevedo/nostr-editor/pull/8

Add explicit support for address quotes

---

11.md

Added banner relay metadata field. 
If nostr relay management is not to be relegated to PhD or protocol developers only, an effort should be made by relay owners to communicate with non-dev non-technical nostr end users. A banner is a visual representation of the relay. It should aim to visually communicate the brand of the relay.

Update 11.md with banner, and icon fields

---

22.md

Please read [here](https://github.com/arthurfranca/nips/blob/comment/22.md)

NIP-22 - Comment

---

README.md

i am not sure what the policy is for what to add to the table, but NIP-35 is completely unmentioned. Add all the tags used.

readme: Add standardized tags to table for NIP-35 (torrents)

---

29.md

Reflecting some of the latest developments.
See each commit independently.
Let me know if it sucks.
@pablof7z @verbiricha @ismyhc @sepehr-safari @water783

NIP-29: some small tweaks

---

README.md

Added kind 1111 and marked kind 10 and kind 12 as deprecated. See #1574 for deprecation of kinds.

update kinds table.

---

10.md

De-emphasizes old stuff. Just moved it to the bottom.

NIP-10 Text Improvement - Moves deprecated stuff to the bottom

---

11.md
17.md
22.md
29.md
46.md
96.md

The file type of commented json has been changed from js or json to jsonc.

Fix file type (js, json -> jsonc)

---

47.md

This allows the wallet service to asynchronously send notifications to connected clients as an alternative to polling.
Example usecases:
- Realtime balance, invoice status, and transaction list updates
Currently two notification types are defined - `payment_received` and `payment_sent`.
This has been implemented in:
- Alby's Nostr Wallet Connect app ("Next" version) https://github.com/getAlby/nostr-wallet-connect-next/pull/183
- Alby JS SDK https://github.com/getAlby/js-sdk/pull/217
- BTCPayServer (Nostr Plugin) https://github.com/Kukks/NNostr/blob/master/NNostr.Client/Protocols/NIP47.cs#L182
- http-nostr https://github.com/getAlby/http-nostr
- [YANA](https://yana.do/)
- [Alby Go](https://github.com/getAlby/go)
There are also some minor copy updates to communicate that NWC is not just for …

NIP-47 notifications

---

29.md

Instead of allowing human-readable ids, it's probably better to just allow users to name groups. I opted for a `petnames` strategy here instead of recommending sending `9002` events or something. Clients can choose whatever heuristic they want to resolve conflicts.

Add support for naming unmanaged groups

---

46.md

Fixes https://github.com/nostr-protocol/nips/issues/1596
Technically backwards incompatible, so should be added to breaking.md after merge. But in practice this was underspecified and doesn't currently work.

Clarify nostrconnect metadata

---

51.md

This is so that users can advertise what relays/groups they are members of. Flotilla uses this to recommend relays. These of course should be considered non-canonical because the users publishing them may not actually have access to the relay specified.

Add r to kind 10009

---

68.md

Adds a simple kind for picture-first clients building Instagram-like feeds, where the picture should be attenuated and the descriptions are less important and might not even be displayed in the main UI.
No, I don't think Kind 1s must be reused for these clients. 
And no, NIP-94 became too generic for this.
Read [here](https://github.com/vitorpamplona/nips/blob/instagram/68.md)

Instagram feeds

---

46.md

this is a placeholder PR that should only be merged once the full transition has happened.
| nip44 support   | decrypt | encrypt |
|-----------------|---------|---------|
| gossip          | ✔️      |  ✔️      |
| amethyst          | ✔️      |  ✔️      |
| highlighter          |✔️      |         | 
| snort          | ✔️      | ✔️        | 
| coracle          | ✔️    | ✔️     |
| flotilla          | ✔️    | ✔️     |
| welshman          | ✔️    | ✔️     |
| ndk             | ✔️       | ✔️       |
| nostrify          | ✔️      | ✔️        | 
| nostr-tools     | ✔️      |         |
| go-nostr        |  ✔️     |         |
| rust-nostr      | ✔️      |  ✔️      |
| nak             | ✔️       |         |
| nostr-login     | ✔️       |         |
| window.nostr.js | ✔️      |         |
| ditto …

nip46: abandon nip04 entirely and just use nip44

---

29.md
51.md

Previously we had group names in the `h` tag, which seems unnecessarily verbose. This allows the name to show up once per user, and solves an edge case for when a room has been created/joined, but doesn't yet have any events in it.

Change strategy for naming groups

---

22.md

This is needed to pull comments a user should look at.
cc @vitorpamplona

Add P-tags and p-tags to NIP-22

---

47.md

Minor grammatical edits for clarity.
- "It's" to "its" to show the possessive case intended instead of the contraction
- Correct article from "an" to "a" for the following d letter (consonant sound)
- Minor edit to fix comma splices with a semicolon ( ; ) to clarify two independent thoughts. Somewhat optional, but it clarifies the two long sentences. Period can instead be used instead as a new sentence.

Grammar updates to 47.md

---

51.md

- Introduce app curation sets, used to group applications (for curation, recommendation, organization, backup)
- Minor fixes to release artifact sets, reflecting current usage
Both kinds 30063 and 30267 have been heavily used for months in Zapstore

Update NIP-51 for software applications

---

18.md

From https://github.com/nostr-protocol/nips/discussions/1678

Don't stringify magic-wanded protected events in reposts

---

README.md

kind 32267 in #1336 is not yet merged, but is referenced from kind 30267 app curation sets as the `a` tag value.

add kind 32267 to list.

---

01.md

The reference to 'username', designed as identifying and unique elements often needed to login, is not correct since Nostr has not usernames.
In addition, field descriptions such as “string” are not very meaningful, and not consistent with other parts of the document.

Remove reference to 'username' and update descriptions in metadata

---

10.md

It's obvious now with NIP 22, but I think it is worth declaring to make things 100% clear.

Clearly informs that kind 1 replies can only be used with kind 1 events.

---

55.md

Most people that implements nip 55 don't implement this check since it's just written in the text at the start of the content resolver section and was not in any of the examples

[NIP-55] - Add the rejected permission check in the code samples

---

01.md

The `restricted` prefix is useful in situations where an individual is not whitelisted to write on a relay or has been banned from it. 
For example, [Immortal (websocket/event_handler.go#L125)](https://github.com/dezh-tech/immortal/blob/f0829316f3ea8af478e34cd04ed6c550bdd93559/delivery/websocket/event_handler.go#L125) uses a restricted prefix to send a message when someone who is not whitelisted tries to write on the relay, provided that the whitelist feature is enabled in the configurations.
Additionally, if this event is sent on nostr.wine:
```
["EVENT", {"kind":1,"id":"ba5a810abf66864fcde9ea1d2ecb33c83bd62833923e428540a0d7bccf93be74","pubkey":"79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","created_at":1736858900,"tags":[],"content":"hello from the nostr army …
```

add restricted to standardized machine-readable prefixes

---

53.md

Adds the ability to optionally pin one or more live chat messages by adding the kind `1311` event id to a `pinned` tag.
cc @v0l

NIP-53 Live Events - Optional Pinned Chat Messages

---

17.md

```jsonc
{
"id": "<usual hash>",
"pubkey": "<sender-pubkey>",
"created_at": "<current-time>",
"kind": 15,
"tags": [
["p", "<receiver-1-pubkey>", "<relay-url>"],
["p", "<receiver-2-pubkey>", "<relay-url>"],
["e", "<kind-14-id>", "<relay-url>", "reply"], // if this is a reply
["subject", "<conversation-title>"],
["file-type", "<file-mime-type>"],
["encryption-algorithm", "<encryption-algorithm>"],
["decryption-key", "<decryption-key>"],
["decryption-nonce", "<decryption-nonce>"]
// rest of tags...
],
"content": "<file-url>"
}
```
Kind 15 is used for sending encrypted file event messages:
- `file-type`: Specifies the MIME type of the attached file (e.g., `image/jpeg`, `audio/mpeg`, etc.).
- `encryption-algorithm`: Indicates the encryption algorithm used for encrypting the file. Supported …

Add Kind 15 for Encrypted File message

---

07.md
46.md
55.md

It makes no sense to a signer manage user relays, specially now that we have multiple kinds of relay lists.
What is the point of those relays?
Inbox?
outbox?
dms?
bootstrap?

remove get_relays from signers

---

55.md

* Most devs misses the content resolver section and think the signer will just stop appearing automatically when the user chooses the remember my choice option
* Most clients are using a fixed package name. By not using a fixed package name allows the user to use other signers and helps debugging

[NIP-55] Make it clear how to use the package name and what is the purpose of the intents and content resolvers

---

53.md

Updates live chat messages to remove the need for markers (they are not necessary) and use `q` tags for quotes.

Updates NIP-53 live chat to remove markers and add `q` tags

---

34.md

- Adds an optional `t` tag to NIP-34 repository announcement events. The `t` tag stands for hashtag and can be used for labelling a repository. This is implemented on the yet to be released github-like client called Nestr.
- Added some missing commas between existing tags.

Optional t tag to git repository announcements

---

25.md

Based on all the events I could glance at randomly, it seems that clients are already doing this, thankfully, because having to download a million likes to events you don't care about just to get the ones you care about would be very sad.

nip25: recommend that reactions do not include a million tags

---

17.md

There are no threading requirements for NIP-17, markers are not needed.

NIP-17: Removes the need for markers and adds the use of `q` tags.

---

01.md

Small readability improvement to the `a` tag definition.

NIP-01 `a` tag clarification

---

23.md

I have migrated Amethyst to write only kind `1111` for replies. It will be on the next version. 
@verbiricha

Long form with NIP-22 comments

---

73.md

Currently the `k` for a website comment is defined to be the base URL of the website, without the path.
This seems arbitrary to me and useless because there is basically no circumstance in which someone would want to filter like "give me all comments made in this domain" (in which case it would be simpler to actually have the domain without the scheme as the "k" anyway).
The way the other "k" tags work makes sense, it's always
- "give me all comments made about books"; or
- "give me all comments made about movies"; or
- "give me all comments made about events of this specific kind I'm interested in".
To follow that pattern what we want is a "k" tag that allows
- "give me all comments made about webpages".
For that we just have to pick some arbitrary value that will always be the same for …

nip73: change "k" tags standard for webpage comments to a hardcoded `web`

---

17.md

Fixes  `decryptiion-nonce` tag name and slightly improves the grammar.

NIP-17 Typos and grammar improvements

---

24.md

This PR introduces the birth field to NIP-24, allowing users to specify their birth date. The goal is to enable applications to celebrate users' birthdays and allow other users to notice and join in the celebration, enhancing social interactions.
Defined the format as [day, month, year (optional)].
The year is optional to accommodate users who prefer not to disclose their age.

Add birth field to NIP-24 for birth date representation

---

73.md

Added Blockchain Transactions and Addresses with some examples to NIP-73 (following up on https://github.com/nostr-protocol/nips/pull/1844)
```
bitcoin:address:<bech32, lowercase | base58, case sensitive>
bitcoin:tx:<txid, hex, lowercase>
ethereum:<chainId, integer>:tx:<txHash, hex, lowercase>
ethereum:<chainId, integer>:address:<hex, lowercase>
```
\+ small cosmetic changes (e.g. ordered the table by alphabetical order)

added blockchain transactions and addresses to NIP-73

---

66.md

Make it like all other NIP titles and descriptions

fix: Fix NIP-66 title and description format

---

README.md
b0.md
b7.md

This describes a tiny subset of possible Blossom capabilities, but arguably the most important from the point of view of a most basic Nostr client.
Other Blossom-related functionalities should be added here later if necessary.
Readable: https://github.com/nostr-protocol/nips/blob/19f671e8777f739537a9b5017a46f67c6169956a/b0.md

add B7 NIP for Blossom interaction

---

README.md

Added links to NIP-B0 in "Standardized Tags" section for optional `title` and `published_at` tags.

Add NIP-B0 Standardized Tags to README.md

---

65.md

Why:
Because the author will send their reply to the users tagged in the note. Let's assume the publisher of the note to which the author replied is followed by someone who doesn't follow the author. This user won't find the author's inbox to reply to unless they find their relays list. Also, this user's client won't be able to view the author's profile picture next to their note because they don't find their outbox.
Note:
This was added in d5907d094b4eace1d2269935202f8d4fbcc4c524 and removed in 45f6d598a19321a98592e1f4fdf0b40707871f26 by mistake

NIP-65: Add note about re-publishing kind 10002

---

01.md

From: 
```json
{
"id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>,
"pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
"created_at": <unix timestamp in seconds>,
"kind": <integer between 0 and 65535>,
"tags": [
[<arbitrary string>...],
// ...
],
"content": <arbitrary string>,
"sig": <64-bytes lowercase hex of the signature of the sha256 hash of the serialized event data, which is the same as the "id" field>
}
```
to 
```yaml
{
"id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>,
"pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
"created_at": <unix timestamp in seconds>,
"kind": <integer between 0 and 65535>,
"tags": [
[<arbitrary string>...],
// ...
],
"content": <arbitrary string>,
"sig": …
```

Using yaml to fix NIP-01 JSON formatting

---

51.md

The NIP description says sets can have a `title`, `image` and `description` tag, but the example had a `name`, `picture` and `about`.

Eliminate discrepancy between NIP description and example

---

01.md

- Fixed a typo in reference to NIP-10 ("especifies" → "specifies").
- Clarified that relays SHOULD use the limit value to guide the number of events returned in the initial query.

Fix typo and clarify `limit` filter behavior in event queries

---

25.md

Currently most reaction tags have only one argument, but there are many out there that follow NIP 10, including a relay hint and marker. But I think the marker is basically meaningless in this context.

Add hints to nip 25

---

25.md
README.md

See the discussion [here](https://github.com/nostrability/nostrability/issues/88)
Emojis are a high-fidelity medium of expression subject to a significant amount of interpretation, while +/- reactions are a low-fidelity medium of expression subject to much less interpretation. The two are semantically incompatible ways of reacting to content, and should not be conflated.
Previously, the NIP included a recommendation to interpret emojis as likes/dislikes, but this put a burden on receiving clients to map every possible emoji to a binary sentiment. This is not only a huge mapping, it's also impossible because the same emoji reaction can be used in different contexts to mean different things.
Additionally, some clients created emoji reactions on their users' behalf to indicate certain …

Remove recommendation to map emoji reactions to like/dislike

---

77.md

This is a copy of @hoytech's https://github.com/hoytech/strfry/blob/nextneg/docs/negentropy.md with some small tweaks in the text (not in the protocol) just to have it here somewhere.
https://github.com/nostr-protocol/nips/blob/negentropy/77.md

NIP-77: Negentropy syncing

---

99.md

We are a collective of developers working on the main marketplaces on Nostr, including Shopstr, Cypher, Plebeian, and Conduit. We have been discussing and working on making our projects more interoperable. While NIP-99 is very broad in its use cases, it was lacking specific conventions for e-commerce, which has become the primary use case for developers implementing the specification. This led to custom implementations and unclear methods for implementing e-commerce using NIP-99. This pull request simply adds a link to the specification we are developing and have consensus on, allowing other developers who want to implement NIP-99 for e-commerce to discover how the major developers are approaching it. In this way, we ensure that NIP-99 remains lightweight and allows for broad use cases …

nip99 e-commerce use case extension

---

34.md

comply with changes to NIP-10 made in https://github.com/nostr-protocol/nips/pull/1750

NIP-34: `mention` marker ~> `q` tag NIP-10 update

---

47.md

This is an alternative proposal to https://github.com/nostr-protocol/nips/pull/1531 to upgrade to nip44 without introducing a versioning system.

[NWC] Add an encryption tag to negotiate upgrading to NIP44.

---

66.md

This is mostly a re-write for clarity. Substantial changes:
- Clarification that values may differ from a relay's nip 11 document if the monitor has reason to believe that the relay's advertised policy differs from its actual policy.
- Removed support for setting `d` to npub, it should be a hex pubkey
- Removed support for "global" tags defined by other NIPs (like `p` tags), since those are necessarily ambiguous. Tag semantics should be defined by NIPs.
@dskvr

Clean up nip 66

---

52.md

This PR enhances NIP-52 to enable collaborative calendar management by introducing an approval workflow for calendar event requests. This addresses the limitation where only calendar owners can add events to their calendars.
Currently, NIP-52 only supports calendar owners adding events to their calendars. This prevents collaborative scenarios such as:
- Community event calendars where multiple organizers contribute
- Team calendars with distributed event management
- Conference schedules with multiple speakers/organizers
- Group coordination calendars
The enhancement interprets existing `a` tags on calendar events as **requests** rather than confirmations when they reference calendars owned by others. This creates a natural approval workflow:
1. Users create events with `a` tags …

NIP-52: Add collaborative calendar event request

---

22.md

The kind of an external URL changed from its domain to "web" here bf699c9bc15e16d78a2bd805626e8813446e5d31

nip22: fix example type for external URL

---

25.md

[NIP-25 Reactions](https://github.com/nostr-protocol/nips/blob/master/25.md) has long had a provision for reacting to websites by using a kind `17` event with an `r` tag to link to the website being reacted to.
This is great as it helps nostr bridge into the existing internet - providing a universal social layer with a social graph you can take to any website.
Since the original NIP-25 we have seen the introduction of [NIP-73](https://github.com/nostr-protocol/nips/blob/master/73.md) which outlines a more extensible method for tagging any external content such as podcasts, books, movies, geohashes, papers, and also urls.
This PR replaces the old `r` tags with NIP-73  `k` and `i` tags as a way of reacting to any external content.
Fountain recently added podcast episode likes using this …

NIP-25: Add External Content Reactions

---

11.md

A limit set to 0 means the relay should not return any events according to NIP-01. This is a subtle but important mistake in NIP-11.

NIP-11: fix default_limit

---

47.md

Libraries that implement the spec strictly and validate fields after https://github.com/nostr-protocol/nips/pull/1933 will lose backward compatibility, since the new field is not marked as `optional`.
This is contrary to the stated intention of making it backward compatibility in the PR:
> This change is backward-compatible and aims to improve UX for clients fetching payments.
This has already happened in https://github.com/rust-nostr/nostr/pull/1021 .
This PR simply adds `// optional` to the field so that libraries developers know they should not strictly require its presence.

NIP-47: mark "state" field as optional in make_invoice response for backward compatibility

---

99.md

This confused me for a moment. I assume "status" should not be in the "price" tag, so I removed the extra bullet point.

Fix weird list in NIP-99

---

42.md

I am adding multi-user feeds on Amethyst: I am blending all logged-in users as one in the interface. 
I can do one new connection for each user, but this may create 3-4 connections per IP for each relay and duplicate all filters, which feels very wasteful and may hit some of the anti-spam measures on relays. 
This PR reuses one connection for everyone by accepting multi-user logins on the relay side. 
It also standardizes what should happen when multiple AUTH messages are returned from clients instead of leaving it as undefined behavior. Today, most relays override the previous AUTH, which means I could keep rotating the authenticated user in the same connection. Others authenticate just the first AUTH ignore all the others. A few of the new ones already work with multiple users in the …

Allow multi-user AUTH

---

71.md

Should these generally be quoted or is it just my client that's rejecting them without?

Quote values

---

47.md

In https://github.com/nostr-protocol/nips/pull/2063 it was not 100% clear how the zap metadata should look - that it should be the full zap request.

docs: clarify NIP-47 zap request metadata

---

66.md

During the edit of NIP-66 by @staab, there were a number of particularly broken changes that were introduced. It was titled "Fix NIP-66" but it actually broke it. 
I brought this up, but was ignored (#1415). In the PR **not only I am the only person in the conversation who has implemented NIP-66, from every possibly angle, I am also the original author**. 
1. The modification `!k` as unaccepted kinds. This is incorrect and makes the key unindexable. The correct usage would be `['k', '!12345']`
2. The `l` tag is not part of NIP-66
The PR was merged without any rationale or considering any feedback. It was merged without consensus or approval by anyone who has implemented NIP-66.
There were other things removed that probably should not have been, namely methodology, but is less important.

Fix fundamentally incorrect assertions in NIP-66

---

47.md

This PR documents a standard for using deeplinks to communicate between a wallet and a nostr client.
The mobile app checks if there is a handler for nostrnwc:// or a handful of nostrnwc+{known_nwc-capable_wallets}://  -- if one is found, the app can open the app via a deeplink and receive the NWC pairing code back from the wallet.

NWC Deep Links
