16.md

Yes, I did modify NIP-12 because I couldn't come up a template by myself. Fixing an artifact left from that

nip16: small fix

---

25.md
README.md

:+1: 
https://github.com/nostr-protocol/nips/blob/reactions/25.md

NIP-25: Reactions

---

25.md

Signed-off-by: William Casarin <jb55@jb55.com>

reactions: we should be able to react to any note

---

35.md
NN-user-discovery.md
README.md

Draft for comments.
It will need to be assigned a number before being merged.

NIP-35 User Discovery

---

13.md

Minor grammar fixes at lines 9 and 93.

Minor grammar fixes

---

05.md

Minor grammar fix at line 48. Minor spelling fix at line 56.

Minor grammar and spelling fixes

---

07.md

as per conversation in t.me/nostr_protcol
getRelays, nip04.encrypt and nip04.decrypt - these are already implemented by nos2x and getalby.

nip-07: add the missing functions

---

05.md

address issue #127
add security constraints to mitigate XSRF properties in NIP-05

update NIP-05 addressing reflectivity.

---

25.md

25.md:15: interepreted ==> interpreted

25.md:15: interepreted ==> interpreted

---

22.md

NIP-22: use nip-20; minor updates

---

25.md

This should be allowed to be considered a dislike for emojis like :-1: :vomiting_face: :rage:

NIP-25: allow for emojis to be considered dislikes

---

21.md
README.md

https://github.com/nostr-protocol/nips/blob/urlscheme/21.md

add NIP-21, `nostr:` url scheme

---

50.md

Based on the discussions at note15djknj3kh6szcj82pp6sm98vk3pw40fg8ajsx8mrpfg3zadyeqhqfmsl2n

Rewrite NIP-50, 'keywords' changed to 'search`

---

50.md

Fixing a typo on NIP-50.
cc @brugeman

Fix NIP-50 typo

---

README.md

Add `kind` 1000-9999 per NIP-16 ~~and 6 "boosts" (no NIP?)~~

Update README.md kind table

---

README.md

I accidentally forgot to add it to the main list in the README

Put NIP-65 in the readme contents

---

README.md

Sorting NIP-56 before the NIP-57 in the `README.md`

Fix readme sorting NIP-56/57

---

58.md

clarify "accept" in "Profile Badges Event" description

Clarify "Profile Badges Event" description in NIP 58.md

---

58.md
README.md

Adds event kind 8 meaning Badge and event kind 30008 parameterized replaceable event meaning Profile Badge.

docs: add nip-58 badge event and profile badges

---

10.md

relay hint language update

---

README.md

fixed a tiny tipo

---

33.md

Fixed example so that the statement is true:
> Events from the same author with any of the following `tags`
replace each other:

NIP-33: Fixed example with multiple values

---

11.md

Take the proposed changes from https://github.com/nostr-protocol/nips/pull/163 and put them in NIP-11 under "Extra Fields"

Add proposed extensions to NIP-11

---

07.md

[horse](https://github.com/fiatjaf/horse) support NIP07

doc: add `horse` extension for NIP07

---

04.md
05.md
11.md
13.md
22.md
25.md
40.md
45.md
51.md
78.md

Did a basic typo and grammar check. Fixed errors.

fix grammar and typos

---

11.md

Just JSON quoting, and a couple missing close brackets.

JSON quoting (and other fixes)

---

27.md

This PR just add links to NIP-21

Add links to NIP-21

---

15.md

Fix for one typo and micro-improvement for a property description

nip-15 typo + micro-fix

---

README.md

Add missing tag `content-warning`

Markdown improvements - README

---

21.md

Add links to NIP-19 in NIP-21

---

11.md

It took me awhile to work out the curl command that would pull back the response.  I think others will find this useful.

NIP11 example using curl.

---

07.md

Added link to another signer extension.

Add new signing extension to NIP-07

---

07.md

When user vist website in nostrmo. The website can access and use nostr object.

Update 07.md Implementation

---

89.md

This PR describes what we've been discussing for a couple of weeks: kind-specific application handlers.
https://github.com/pablof7z/nips/blob/application-handlers/89.md
cc @fiatjaf @staab @brugeman

NIP-89: Recommended Application Handlers

---

09.md

Remove the trailing comma in the tags array.

Minor JSON fix

---

09.md

Simple change to explicitly mention NIP-33 event deletion

NIP-09: Add `a` tag deletion

---

11.md

Add optional image to Relay Information Document.

NIP-11: add optional image

---

25.md

The content for reactions might be NIP-30 custom emoji.

NIP-25 content might be NIP-30 custom emoji

---

14.md
README.md

This is also unimportant and a very minor fix.

Fix titles

---

23.md

Link: https://groups.google.com/g/nostr-protocol/c/tnrcWTIAzdU

nip23: add some formatting guidelines to maximize compatibility

---

53.md

Everywhere else in the NIP 30311 is used

Fix event kind in example in NIP 53

---

25.md

Seems like a bunch of clients assume this so it should be documented

NIP-25: Handle empty string as +

---

65.md

This is how I would write this, @mikedilger 
If this is wrong, ignore it. 
Read [here](https://github.com/vitorpamplona/nips/blob/nip-65-simplified/65.md).

Simplifies NIP-65

---

README.md

Related: https://github.com/nostr-protocol/nips/commit/f89187a2581aceb99c436d5919391622a82b0713

Update NIP-50 title in list

---

19.md

See https://github.com/nostr-protocol/nips/issues/657 for the discussion

Define how to encode a non-parameterized replaceable event as a naddr

---

11.md

I was talking to CloudFodder and had this idea. Just wanted to see if it is needed and rough draft it during exploration

Add NIP-22 created_at limits to "limitations"

---

38.md

* content may include custom emoji
* empty content means clear status

NIP-38: description for content

---

24.md

A relay list of kind 3 is not written anywhere and is not clear.
Is the relay list unnecessary? Or is it wrong to write in NIP-24?

Add relay list of kind 3 to NIP-24

---

65.md

Update from discussion on #798. 
Does this need more explicit clarification is this sufficient?

65: Normalize relay URIs

---

07.md

Add Spring.site as NIP07 implementation

add spring.site to nip-07

---

57.md

Clarify how multiple relays should be included in the zap request event

NIP-57: Clarify multiple relays in zap request event

---

README.md

Now kinds of job feedback and job result are changed to 7000 and 6000-6999 at d9400e1e7b08225aedb6c78b522c5ad07b5198b4 in #682

DVM kinds change on README

---

07.md

Finally getting around to adding Nostore to the NIP-07 extension list.

Adding Nostore to NIP-07 extension list.

---

89.md

As a result of this discussion: nostr:nevent1qqstw8cw0nw50le9uugahpze78q9y0j90swhgan636ac08acmkn6v0gpz3mhxue69uhhyetvv9ukzcnvv5hx7un89uqs6amnwvaz7tmzwf3zu6t09uq3wamnwvaz7tmjv4kxz7fwwvehstnnda3kjctv9uqsuamnwvaz7tmwdaejumr0dshsz9mhwden5te0wfjkccte9ehx7um5wghxyctwvshsz9mhwden5te0dehhxarj9eex2mrp09jhytnnv5hszyrhwden5te0v5hxummn9ekx7mp0qyfhwumn8ghj7ur4wfcxcetsv9njuetn9uq3xamnwvaz7tm0venxx6rpd9hzuur4vghszxthwden5te0wfjkccte9eekummjwsh8xmmrd9skctcku97e5

Add client tag to nip 89

---

README.md

Reorder `alt` tag and add `client` and `encrypted` tags defined in NIP-89 and 90, respectively.

Update tag list

---

02.md
README.md

Nostrbros take for granted that they once looked at the list of NIPs and couldn't figure out how to follow people. For example: https://github.com/nbd-wtf/nostr-tools/issues/322
It should be abundantly clear how to do this very basic feature of social network on the Nostr protocol.

NIP-02: Rename Contact List to Follow List

---

46.md

this is an attempt to simplify the text, remove garbage and incorporate the lessons from nsecbunker implementation.
result: https://github.com/nostr-protocol/nips/blob/nostr-connect/46.md

rewrite NIP-46

---

44.md

Increases trust in the specification

nip-44: add audit notice

---

01.md

Reword REQ for multiple filters

---

README.md

I didn't want to touch all that white-space in #941, but here you go @vitorpamplona 😉

Rephrase deprecation of kind 2

---

46.md
58.md

nip-46: fix typo
nip-58: fix typo

nip-46,nip-58: fix typos

---

51.md

The thought is to enable users to create playlists or better categorized lists of videos

Update 51.md to add support for video lists

---

02.md
51.md

Fixes https://github.com/nostr-protocol/nips/issues/958

NIP-02, NIP-51: new tags should be added to the end of the list

---

96.md

fix typo `successfull` -> `successful`

NIP-96: fix typo

---

README.md

Add kinds for NIP-15

---

01.md

```patch
-Relays can send 4 types of messages, [...]: EVENT, OK, EOSE, CLOSED, NOTICE
+Relays can send 5 types of messages, [...]: EVENT, OK, EOSE, CLOSED, NOTICE
```

fix(docs): typo in 01.md

---

51.md
README.md

Groups of kind 1063 File Metadata events

File metadata sets

---

BREAKING.md
README.md

This is my attempt to start a list of potentially breaking changes. When we merge in a new NIP that we think might have a breaking change, even a subtle one, we can include it on this list.
Nostr changes fast, but most changes are typo corrections, and then there is a lot of stuff added that doesn't break anything. Developers who are too busy to keep up all the time can really benefit from this list to make sure they have kept up.
I think enough of us care that we can keep this list maintained.

Breaking changes list

---

49.md

One of these commits was already merged. I just pushed another commit on top of it.

NIP-49 test vector for unicode normalization

---

BREAKING.md

No one seems to care, but a list that is not updated has no value.

BREAKING.md: add NIP-18 change

---

README.md

README: add kinds and tags for NIP-34

---

96.md

NIP-96: simplify server list

---

05.md

Changes relays attribute from optional to recommended

Recommend setting relays in NIP05

---

46.md

This is implemented in nsec.app, nostr.band, Coracle and Nostrudel, so maybe it's time to update the NIP.

Add optional_requested_permissions

---

34.md

see commit messages for more details

NIP-34: add Status events, clarifications and improvements

---

01.md

Require tags to have at least one string

---

90.md

The headers changed which broke these links.

nip90: fix links

---

README.md

README: remove `l` tag annotations

---

BREAKING.md

As for NIP-25, I'm not sure if it is a breaking change or not.

BREAKING.md: add changes

---

24.md

NIP-24: fix missing rename

---

01.md

A few small changes that can potentially help a broader audience (non-developers) follow the meaning.

parentheses > commas

---

29.md

nip29: create-group event kind

---

65.md

NIP-65: fix typo

---

BREAKING.md

BREAKING.md: add NIP-01 change

---

09.md

Add k tag to deletions

---

32.md

https://github.com/nostr-protocol/nips/pull/632#issuecomment-2248687848
Feel free to make any changes, thanks.

NIP-32: Language example

---

45.md
README.md

Reverts nostr-protocol/nips#842

Revert "Remove NIP 45 COUNT"

---

BREAKING.md

Maybe this is meaningless, but I just record the fact.

BREAKING.md: add NIP-45 changes

---

25.md
README.md

Define `kind 17` event to react to a website.
It includes an `r` tag with the website's URL.
I want to react to a website with a decentralized system.
#1380

NIP-25: reactions to a website

---

29.md

- kind 9008: `delete group` "admin permission"
- kind 9022: `leave request`

Nip29 enhancements

---

17.md

NIP-17 Fix kind number 

---

05.md

One clarification that I think it is useful to add in the NIP, as a result of [this thread](https://njump.me/nevent1qqsrpvvhnu5fu8gaudnlnuk7cdp3m5yezl6w88x9t38c3zdhaju52tcpzamhxue69uhky6t5vdhkjmn9wgh8xmmrd9skctcpr9mhxue69uhkxcfwwp6hyurvv4ex2mrp0yhxxmmd9uqjqamnwvaz7tmrdphhyatn9ekkj6m9v35kcem9wghxxmmd8g6rgdp0wukeu8).

NIP-05: add identification vs verification note

---

44.md

Community member wasted time because of that.

nip44: clarify ecdh hashing

---

13.md

Fixes https://github.com/nostr-protocol/nips/commit/6fb9e54f7b4886272f7464aba2f0971543d8df40#commitcomment-146061197

Revert example code update

---

30.md

custom emojis in reactions

---

34.md
README.md

Issues usually have headers and self reported labels.

Add `subject` and `t` tags to git issues

---

96.md

fix typo on nip96

---

01.md

Fixes https://github.com/nostr-protocol/nips/issues/1520

Clarify tag filters

---

BREAKING.md
README.md

README, BREAKING.md: update related to NIP-71

---

24.md

Adds pronouns

---

README.md

update related to NIP-29.

---

86.md
87.md
README.md

https://github.com/nostr-protocol/nips/blob/relay-management-api/86.md
Based on discussions at https://t.me/+BBS3jWGU9C1lYTRh

add NIP-86: Relay Management API

---

44.md

"Encoding algorithm" instead of "compression algorithm"

NIP-44: Proper base64 explanation

---

17.md

Order specificity is implied better.

nip17: specify order

---

94.md

i think this is event `kind`, not type.

fix typo in nip-94.

---

32.md

the current link is broken. i think we can replace it with this.

fix broken link.

---

README.md

rename NIP-44 in readme.

---

59.md

Just came across what I think is a typo

Update nip 59 typo

---

README.md

Drafts are only one of the many types of private events, which [NIP-37](https://github.com/nostr-protocol/nips/blob/master/37.md) mentions as well. This PR updates the description of kind 10013 in the README to be consistent.

Update kind 10013 description in README

---

57.md

https://njump.me/nevent1qyw8wumn8ghj7cn4vd4k2apwvdhhyctrd3jjuum0vd5kzmp0qy88wumn8ghj7mn0wvhxcmmv9uq3samnwvaz7tmrv4kxcctj9ehx7um5wgh8w6twv5hsz3thwden5te0v33rgetxda382uejd9k8garhx4nk76mrwa3kkvm0dd3hydphxe58z6md09ckgat009ukgmr0xf4rw6tfvajks6mevshxcmmrv9kz7qgnwaehxw309ahkvenrdpskjm3wwp6kytcqyznz66q53w6tqa38w2088z7028jcvelnvpl3dcv9c3pmnq0ay44nzjc7wxd

Make description_hash verification optional

---

22.md

NIP-22: what is an I-tag?

---

47.md

Some places in the spec are a bit unclear especially around key usage.

docs: clarify NIP-47 key usage

---

61.md

I forgot this one in the last merge request

NIP-61: nitpick

---

61.md

61: nitpick

---

README.md

add NIP-56 link to `x` tag.

---

95.md

Reference implementations: 
- https://notebin.io
- https://snipsnip.dev

NIP-C0: Code snippets

---

README.md

https://github.com/nostr-protocol/nips/blob/f90101406592134e5f9c27c5e81fad3ee670e9c1/C0.md?plain=1#L15-L24

NIP-C0: Add `NIP-C0` tags to standardized tags table

---

65.md

Attempt to fix https://github.com/nostrability/nostrability/issues/166
The language here is awkward, feel free to suggest changes.

Add note about re-publishing kind 10002

---

65.md

Following https://github.com/nostr-protocol/nips/issues/1876#issuecomment-2806555636.

Shrink NIP-65 so it is clearer

---

7D.md

This seems to be what Flotilla and Chachi are doing.
@staab 
@verbiricha 
@wcat7 
@mplorentz 
@haorendashu

nip7D: `subject` -> `title`

---

11.md

added privacy policy, and terms of service to NIP-11

Update 11.md with privacy policy and terms of service

---

69.md
88.md
C0.md

Sorry, I didn't notice those when I submit my previous pull request #1886

Fix nips titles and descriptions

---

b0.md

In addition of https://github.com/nostr-protocol/nips/pull/1847

adding more info / requirements for using kind 39701 for web bookmarks (NIP-B0)

---

README.md

In addition of https://github.com/nostr-protocol/nips/pull/1849

Add kind 39701 web bookmarks to list of kinds in readme

---

51.md
README.md

Add a favorite relays kind to store users' favorite relays and pointers to relay sets

NIP-51: favorite relays

---

19.md

replaceable -> addressable

---

25.md

nip25: remove duplicate

---

README.md

This could have been a real NIP, I'm not sure why @chadcurtis closed https://github.com/nostr-protocol/nips/pull/1943. It also re-uses a kind defined in https://github.com/nostr-protocol/nips/pull/927. @arkin0x how much does this mess things up for you?

Add geocaching kinds

---

03.md
18.md
57.md
61.md

include missing "k" tag in some reactions

---

72.md

Before:
* (h1) NIP-72
* (h2) Moderated Communities (Reddit Style)
* (h1) Community Definition
* (h1) Posting to a community
* (h2) Top-level posts
* (h2) Nested replies
* (h2) Backwards compatibility note
* (h1) Moderation
* (h1) Cross-posting
After:
* (h1) NIP-72
* (h2) Moderated Communities (Reddit Style)
* (h2) Community Definition
* (h2) Posting to a community
* (h3) Top-level posts
* (h3) Nested replies
* (h3) Backwards compatibility note
* (h2) Moderation
* (h2) Cross-posting

NIP-72: Fix heading levels

---

B0.md

clean up B0.

---

README.md

add NIP-EE kinds
